CREATE TABLE mytable(
   id               INTEGER  NOT NULL PRIMARY KEY 
  ,name             VARCHAR(16) NOT NULL
  ,cardType         VARCHAR(7) NOT NULL
  ,state            VARCHAR(6)
  ,evolvesFrom      VARCHAR(10)
  ,cardFunction     VARCHAR(51)
  ,monsterHP        INTEGER 
  ,Skill1DMG        INTEGER 
  ,Skill1EnergyQty  INTEGER 
  ,Skill1EnergyType VARCHAR(33)
  ,Skill1Effect     VARCHAR(4)
  ,Skill2DMG        INTEGER 
  ,Skill2EnergyQty  INTEGER 
  ,Skill2EnergyType VARCHAR(33)
  ,Skill2Effect     VARCHAR(4)
);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (1,'Zubat','Monster','Basic',NULL,NULL,50,0,1,'DarkEnergy',NULL,20,2,'AllEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (2,'Hirahina','Monster','Basic',NULL,NULL,50,10,1,'PsychicEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (3,'PaldeaUpaa','Monster','Basic',NULL,NULL,60,10,1,'DarkEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (4,'PaldeaUpaa','Monster','Basic',NULL,NULL,60,10,1,'DarkEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (5,'Bochi','Monster','Basic',NULL,NULL,80,20,2,'AllEnergy,AllEnergy',NULL,50,3,'PsychicEnergy,AllEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (6,'Bochi','Monster','Basic',NULL,NULL,80,20,2,'AllEnergy,AllEnergy',NULL,50,3,'PsychicEnergy,AllEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (7,'Otoshidori','Monster','Basic',NULL,NULL,120,20,1,'AllEnergy',NULL,120,3,'DarkEnergy,DarkEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (8,'Buroron','Monster','Basic',NULL,NULL,60,0,1,'AllEnergy',NULL,20,2,'MetalEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (9,'Mamebatta','Monster','Basic',NULL,NULL,50,20,1,'AllEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (10,'Mamebatta','Monster','Basic',NULL,NULL,50,20,1,'AllEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (11,'Celeby','Monster','Basic',NULL,NULL,80,0,1,'AllEnergy',NULL,30,1,'GrassEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (12,'Nonokurage','Monster','Basic',NULL,NULL,60,10,1,'GrassEnergy',NULL,20,2,'GrassEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (13,'Koromori','Monster','Basic',NULL,NULL,60,30,1,'PsychicEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (14,'Sakebushippo','Monster','Basic',NULL,NULL,90,20,1,'PsychicEnergy',NULL,0,2,'PsychicEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (15,'Eksleg','Monster','Stage1','Mamebatta',NULL,120,60,1,'DarkEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (16,'Eksleg','Monster','Stage1','Mamebatta',NULL,120,60,1,'DarkEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (17,'Kokoromori','Monster','Stage1','Koromori',NULL,90,30,1,'PsychicEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (18,'Kuesupatora','Monster','Stage1','Hirahina',NULL,130,50,1,'PsychicEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (19,'PaldeaDooEX','Monster','Stage1','PaldeaUpaa',NULL,280,60,2,'DarkEnergy,AllEnergy',NULL,220,3,'DarkEnergy,DarkEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (20,'Golbat','Monster','Stage1','Zubat',NULL,80,30,2,'AllEnergy,AllEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (21,'Kurobat','Monster','Stage2','Golbat',NULL,130,50,2,'AllEnergy,AllEnergy',NULL,130,3,'DarkEnergy,AllEnergy,AllEnergy',NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (22,'HakadogEX','Monster','Stage1','Bochi',NULL,260,100,3,'PsychicEnergy,AllEnergy,AllEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (23,'Rikukurage','Monster','Stage1','Nonokurage',NULL,130,130,3,'FightEnergy,AllEnergy,AllEnergy',NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (24,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (25,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (26,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (27,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (28,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (29,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (30,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (31,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (32,'PsychicEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (33,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (34,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (35,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (36,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (37,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (38,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (39,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (40,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (41,'DarkEnergy','Energy',NULL,NULL,'"add energy to Monster"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (42,'FushiginaAme','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (43,'MonsterBall','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (44,'MonsterBall','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (45,'HyperBall','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (46,'BoostEnergyKodai','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (47,'PokemonCatcher','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (48,'PokemonCatcher','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (49,'SuperBall','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (50,'SuperBall','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (51,'PokemonIrekae','Goods',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (52,'Nemo','Support',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (53,'Nemo','Support',NULL,NULL,'"draw 3 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (54,'Tanpankozou','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (55,'Tanpankozou','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (56,'KarateOunoKeiko','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (57,'Nanjamo','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (58,'HakasenoKenkyuu','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (59,'Judgeman','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(id,name,cardType,state,evolvesFrom,cardFunction,monsterHP,Skill1DMG,Skill1EnergyQty,Skill1EnergyType,Skill1Effect,Skill2DMG,Skill2EnergyQty,Skill2EnergyType,Skill2Effect) VALUES (60,'PicnicGirl','Support',NULL,NULL,'"discard all cards in hands to trash. Draw 7 cards"',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
